title: Blogs and jokes
theme: minima
author: Martin Vollmann
email: martin.vollmann@gmail.com
description: > # this means to ignore newlines until "baseurl:
  In this page I will share blogs about physics, science and who knows?!
  maybe also music
# social links
twitter_username: mertio1 # DO NOT include the @ character, or else the build will fail!
github_username:  mertio1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
